package imap

import (
	"bufio"
	"net"
	"strings"
	"testing"
	"time"

	"github.com/emersion/go-imap/v2/imapclient"
	"github.com/rs/zerolog"
)

// loginThenSilentServer speaks just enough IMAP to let a client log in and
// then never answers anything again — the exact shape of the failure task
// 3-16 is about: a server that accepts LOGOUT but withholds the reply.
type loginThenSilentServer struct {
	ln net.Listener
}

func newLoginThenSilentServer(t *testing.T) *loginThenSilentServer {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	s := &loginThenSilentServer{ln: ln}
	go s.serve()
	t.Cleanup(func() { _ = ln.Close() })
	return s
}

func (s *loginThenSilentServer) serve() {
	conn, err := s.ln.Accept()
	if err != nil {
		return
	}
	defer conn.Close()

	r := bufio.NewReader(conn)
	// Greeting first: the client blocks on it before it will send anything.
	if _, err := conn.Write([]byte("* OK [CAPABILITY IMAP4REV1] stub ready\r\n")); err != nil {
		return
	}
	loggedIn := false
	for {
		line, err := r.ReadString('\n')
		if err != nil {
			return
		}
		if !loggedIn {
			fields := strings.Fields(line)
			// The tag is generated by the client, so match on the command.
			if len(fields) >= 2 && strings.EqualFold(fields[1], "LOGIN") {
				if _, err := conn.Write([]byte(fields[0] + " OK logged in\r\n")); err != nil {
					return
				}
				loggedIn = true
			}
		}
		// Everything after LOGIN — including LOGOUT — is read and discarded
		// without a reply, and the connection stays open.
	}
}

func quietLogger() zerolog.Logger { return zerolog.Nop() }

// TestCloseBoundedWhenServerNeverAnswersLogout is the runnable check for Phase 3
// task 3-16: a server that accepts the connection and then never answers
// LOGOUT must not make Close() block. Before the fix, Logout().Wait() hung here
// indefinitely and pinned the IDLE goroutine plus its Pool slot.
func TestCloseBoundedWhenServerNeverAnswersLogout(t *testing.T) {
	prev := closeTimeout
	closeTimeout = 200 * time.Millisecond
	t.Cleanup(func() { closeTimeout = prev })

	srv := newLoginThenSilentServer(t)
	conn, err := net.Dial("tcp", srv.ln.Addr().String())
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	inner := imapclient.New(conn, nil)
	if err := inner.Login("user", "pass").Wait(); err != nil {
		t.Skipf("stub login not accepted (%v); test needs a working greeting handshake", err)
	}

	c := &Client{client: inner, log: quietLogger()}

	start := time.Now()
	done := make(chan struct{})
	go func() {
		_ = c.Close()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(10 * time.Second):
		t.Fatal("Close() blocked on a server that never answers LOGOUT; the graceful logout is still unbounded")
	}

	// The server never replies, so Close() can only have returned by hitting
	// the timeout and forcing the socket down. Anything faster would mean the
	// test is not exercising the bound at all.
	if elapsed := time.Since(start); elapsed < closeTimeout {
		t.Errorf("Close() returned after %v, faster than the %v logout bound — the silent-server scenario is not being exercised", elapsed, closeTimeout)
	}
}

// TestForceCloseAlsoReturns is the cheap companion check: the hard path used on
// IDLE error paths must never block either.
func TestForceCloseAlsoReturns(t *testing.T) {
	srv := newLoginThenSilentServer(t)
	conn, err := net.Dial("tcp", srv.ln.Addr().String())
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	inner := imapclient.New(conn, nil)
	if err := inner.Login("user", "pass").Wait(); err != nil {
		t.Skipf("stub login not accepted (%v)", err)
	}
	c := &Client{client: inner, log: quietLogger()}

	done := make(chan struct{})
	go func() {
		_ = c.ForceClose()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(10 * time.Second):
		t.Fatal("ForceClose() blocked on a silent server")
	}
}

// TestTakeClientDetachesUnderLock checks the invariant task 3-16 introduced:
// the socket is detached while the mutex is held and handed back so it can be
// closed outside the lock.
func TestTakeClientDetachesUnderLock(t *testing.T) {
	ic := &IdleConnection{}
	if got := ic.takeClient(); got != nil {
		t.Fatalf("takeClient on an empty connection = %v, want nil", got)
	}

	sentinel := &imapclient.Client{}
	ic.client = sentinel

	got := ic.takeClient()
	if got != sentinel {
		t.Fatalf("takeClient = %p, want %p", got, sentinel)
	}
	if ic.client != nil {
		t.Fatal("client field still set after takeClient")
	}
	if again := ic.takeClient(); again != nil {
		t.Fatal("takeClient handed out the same socket twice")
	}
}
